clean:
	rm -f -r *.elf *.bin *.map *.inc *.o

all:
	make -f Makefile clean
	make -f Makefile_355C.mak
	make -f Makefile_355C.mak code
	cp erk_payload_355C.inc ../source/erk_payload_355C.shellcode.inc
	rm -f *.elf *.o *.map *.inc
	make -f Makefile_355D.mak
	make -f Makefile_355D.mak code
	cp erk_payload_355D.inc ../source/erk_payload_355D.shellcode.inc
	rm -f *.elf *.o *.map *.inc

	make -f Makefile_421C.mak
	make -f Makefile_421C.mak code
	cp erk_payload_421C.inc ../source/erk_payload_421C.shellcode.inc
	rm -f *.elf *.o *.map *.inc
	make -f Makefile_421D.mak
	make -f Makefile_421D.mak code
	cp erk_payload_421D.inc ../source/erk_payload_421D.shellcode.inc
	rm -f *.elf *.o *.map *.inc
	make -f Makefile_421E.mak
	make -f Makefile_421E.mak code
	cp erk_payload_421E.inc ../source/erk_payload_421E.shellcode.inc
	rm -f *.elf *.o *.map *.inc

	# make -f Makefile_430C.mak
	# make -f Makefile_430C.mak code
	# cp erk_payload_430C.inc ../source/erk_payload_430C.shellcode.inc
	# rm -f *.elf *.o *.map *.inc
	# make -f Makefile_430D.mak
	# make -f Makefile_430D.mak code
	# cp erk_payload_430D.inc ../source/erk_payload_430D.shellcode.inc
	# rm -f *.elf *.o *.map *.inc

	make -f Makefile_446C.mak
	make -f Makefile_446C.mak code
	cp erk_payload_446C.inc ../source/erk_payload_446C.shellcode.inc
	rm -f *.elf *.o *.map *.inc
	make -f Makefile_446D.mak
	make -f Makefile_446D.mak code
	cp erk_payload_446D.inc ../source/erk_payload_446D.shellcode.inc
	rm -f *.elf *.o *.map *.inc

	# make -f Makefile_465C.mak
	# make -f Makefile_465C.mak code
	# cp erk_payload_465C.inc ../source/erk_payload_465C.shellcode.inc
	# rm -f *.elf *.o *.map *.inc
	# make -f Makefile_465D.mak
	# make -f Makefile_465D.mak code
	# cp erk_payload_465D.inc ../source/erk_payload_465D.shellcode.inc
	# rm -f *.elf *.o *.map *.inc

	# make -f Makefile_470C.mak
	# make -f Makefile_470C.mak code
	# cp erk_payload_470C.inc ../source/erk_payload_470C.shellcode.inc
	# rm -f *.elf *.o *.map *.inc
	# make -f Makefile_470D.mak
	# make -f Makefile_470D.mak code
	# cp erk_payload_470D.inc ../source/erk_payload_470D.shellcode.inc
	# rm -f *.elf *.o *.map *.inc

	make -f Makefile_475C.mak
	make -f Makefile_475C.mak code
	cp erk_payload_475C.inc ../source/erk_payload_475C.shellcode.inc
	rm -f *.elf *.o *.map *.inc
	make -f Makefile_475D.mak
	make -f Makefile_475D.mak code
	cp erk_payload_475D.inc ../source/erk_payload_475D.shellcode.inc
	rm -f *.elf *.o *.map *.inc

	# make -f Makefile_476C.mak
	# make -f Makefile_476C.mak code
	# cp erk_payload_476C.inc ../source/erk_payload_476C.shellcode.inc
	# rm -f *.elf *.o *.map *.inc
	# make -f Makefile_476D.mak
	# make -f Makefile_476D.mak code
	# cp erk_payload_476D.inc ../source/erk_payload_476D.shellcode.inc
	# rm -f *.elf *.o *.map *.inc

	# make -f Makefile_478C.mak
	# make -f Makefile_478C.mak code
	# cp erk_payload_478C.inc ../source/erk_payload_478C.shellcode.inc
	# rm -f *.elf *.o *.map *.inc
	# make -f Makefile_478D.mak
	# make -f Makefile_478D.mak code
	# cp erk_payload_478D.inc ../source/erk_payload_478D.shellcode.inc
	# rm -f *.elf *.o *.map *.inc
	rm -f *.bin
